// Seed data for the in-memory store. In production these arrays would be
// replaced by database queries (each export ~ a table). Coordinates are placed
// around MAP_CENTER so everything renders on the live map.

import type {
  Center,
  Driver,
  FleetEvent,
  Participant,
  Vehicle,
} from './types'

const C = { lat: 40.7359, lng: -73.9911 }
// small helper to offset from center in ~km-ish degree units
const o = (dLat: number, dLng: number) => ({
  lat: C.lat + dLat,
  lng: C.lng + dLng,
})

export const seedCenters: Center[] = [
  {
    id: 'ctr-1',
    name: 'City General Hospital',
    type: 'Hospital',
    address: '400 Metro Ave',
    location: o(0.012, 0.004),
    operatingHours: '6:00 AM - 10:00 PM',
    capacity: 320,
  },
  {
    id: 'ctr-2',
    name: 'Riverside Dialysis Center',
    type: 'Dialysis Center',
    address: '88 Riverside Blvd',
    location: o(-0.02, -0.03),
    operatingHours: '5:00 AM - 8:00 PM',
    capacity: 60,
  },
  {
    id: 'ctr-3',
    name: 'Maple Rehabilitation Center',
    type: 'Rehabilitation Center',
    address: '210 Maple St',
    location: o(0.028, -0.02),
    operatingHours: '7:00 AM - 6:00 PM',
    capacity: 90,
  },
  {
    id: 'ctr-4',
    name: 'Sunset Senior Care',
    type: 'Senior Care Center',
    address: '15 Sunset Way',
    location: o(-0.03, 0.028),
    operatingHours: '8:00 AM - 5:00 PM',
    capacity: 120,
  },
  {
    id: 'ctr-5',
    name: 'Eastside Community Hall',
    type: 'Community Hall',
    address: '77 Union Plaza',
    location: o(0.006, 0.034),
    operatingHours: '9:00 AM - 9:00 PM',
    capacity: 250,
  },
  {
    id: 'ctr-6',
    name: 'Northgate Therapy Center',
    type: 'Therapy Center',
    address: '512 Northgate Rd',
    location: o(0.035, 0.012),
    operatingHours: '8:00 AM - 7:00 PM',
    capacity: 70,
  },
]

const noConstraints = {
  wheelchair: false,
  poweredWheelchair: false,
  walker: false,
  oxygen: false,
  caregiverRequired: false,
  bariatric: false,
  visualAssist: false,
  cognitiveAssist: false,
  serviceAnimal: false,
}

let pIdx = 0
function makeParticipant(
  name: string,
  dLat: number,
  dLng: number,
  overrides: Partial<Participant> = {},
): Participant {
  pIdx += 1
  return {
    id: `p-${pIdx}`,
    name,
    phone: `(212) 555-0${100 + pIdx}`,
    emergencyContact: `(212) 555-0${900 - pIdx}`,
    address: `${100 + pIdx * 7} ${['Oak', 'Elm', 'Pine', 'Cedar', 'Birch'][pIdx % 5]} St`,
    location: o(dLat, dLng),
    medicalNotes: '',
    maxTravelMinutes: 40,
    pickupWindow: '7:30 AM - 8:15 AM',
    mobilityLevel: 'independent',
    medicalPriority: 'routine',
    eligible: true,
    status: 'registered',
    eventId: null,
    ...overrides,
    constraints: { ...noConstraints, ...(overrides.constraints ?? {}) },
  }
}

export const seedParticipants: Participant[] = [
  makeParticipant('Eleanor Whitfield', 0.018, -0.028, {
    constraints: { wheelchair: true },
    mobilityLevel: 'wheelchair',
    medicalPriority: 'elevated',
    maxTravelMinutes: 25,
    medicalNotes: 'Requires manual wheelchair; assist boarding.',
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Marcus Bellamy', 0.022, -0.024, {
    constraints: { oxygen: true },
    medicalPriority: 'critical',
    maxTravelMinutes: 20,
    medicalNotes: 'Portable oxygen concentrator, 2L/min.',
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Priya Nair', 0.026, -0.031, {
    constraints: { caregiverRequired: true },
    mobilityLevel: 'assisted',
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Hank Osborne', 0.015, -0.035, {
    constraints: { walker: true },
    mobilityLevel: 'assisted',
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Dorothy Klein', 0.024, -0.038, {
    constraints: { wheelchair: true, oxygen: true },
    mobilityLevel: 'wheelchair',
    medicalPriority: 'critical',
    maxTravelMinutes: 20,
    medicalNotes: 'Wheelchair + oxygen. Needs lift-equipped vehicle.',
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Sofia Ramirez', 0.02, -0.02, {
    constraints: { caregiverRequired: true, cognitiveAssist: true },
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('James Whitaker', 0.03, -0.026, {
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Nadia Farouk', 0.017, -0.022, {
    constraints: { visualAssist: true, serviceAnimal: true },
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Walter Greaves', 0.028, -0.033, {
    constraints: { bariatric: true },
    mobilityLevel: 'assisted',
    medicalNotes: 'Bariatric seating required.',
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  makeParticipant('Grace Lin', 0.013, -0.03, {
    eventId: 'evt-1',
    status: 'scheduled',
  }),
  // Queue for event 2 (therapy) - partially unassigned
  makeParticipant('Theodore Marsh', 0.032, 0.008, {
    constraints: { wheelchair: true },
    mobilityLevel: 'wheelchair',
    eventId: 'evt-2',
    status: 'registered',
  }),
  makeParticipant('Isabella Cruz', 0.038, 0.014, {
    constraints: { walker: true },
    eventId: 'evt-2',
    status: 'registered',
  }),
  makeParticipant('Omar Haddad', 0.03, 0.02, {
    eventId: 'evt-2',
    status: 'registered',
  }),
  makeParticipant('Ruth Feldman', 0.036, 0.006, {
    constraints: { caregiverRequired: true },
    medicalPriority: 'elevated',
    eventId: 'evt-2',
    status: 'registered',
  }),
  makeParticipant('Daniel Okafor', 0.041, 0.016, {
    eventId: 'evt-2',
    status: 'registered',
  }),
  makeParticipant('Helen Petrova', 0.034, 0.022, {
    constraints: { oxygen: true },
    medicalPriority: 'elevated',
    eventId: 'evt-2',
    status: 'registered',
  }),
  // Unassigned pool (no event yet)
  makeParticipant('Arthur Nguyen', -0.025, 0.03, {
    constraints: { wheelchair: true },
    mobilityLevel: 'wheelchair',
  }),
  makeParticipant('Beatrice Sol', -0.03, 0.024, {
    constraints: { walker: true },
  }),
  makeParticipant('Victor Adeyemi', -0.028, 0.032, {}),
  makeParticipant('Lucia Moretti', -0.022, 0.036, {
    constraints: { caregiverRequired: true, cognitiveAssist: true },
    medicalPriority: 'elevated',
  }),
  makeParticipant('George Halloran', -0.018, -0.026, {
    constraints: { oxygen: true },
    medicalPriority: 'critical',
    maxTravelMinutes: 20,
  }),
  makeParticipant('Mabel Thornton', -0.024, -0.03, {
    constraints: { wheelchair: true, bariatric: true },
    mobilityLevel: 'wheelchair',
  }),
  makeParticipant('Rosalind Vance', -0.032, 0.018, {
    mobilityLevel: 'stretcher',
    medicalPriority: 'critical',
    maxTravelMinutes: 20,
    medicalNotes: 'Non-ambulatory; requires gurney-equipped vehicle.',
  }),
]

export const seedVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    name: 'Unit 101',
    address: '100 Madison Ave, New York, NY',
    type: 'Wheelchair Accessible Van',
    capacity: 6,
    wheelchairCapacity: 2,
    oxygenEquipment: true,
    liftAvailable: true,
    bariatricCapable: false,
    stretcherCapable: false,
    fuelType: 'Hybrid',
    maintenanceStatus: 'good',
    status: 'available',
    location: { lat: C.lat + 0.004, lng: C.lng - 0.006 },
  },
  {
    id: 'veh-2',
    name: 'Unit 102',
    address: '250 Broadway, New York, NY',
    type: 'Medical Transport Vehicle',
    capacity: 4,
    wheelchairCapacity: 1,
    oxygenEquipment: true,
    liftAvailable: true,
    bariatricCapable: true,
    stretcherCapable: true,
    fuelType: 'Diesel',
    maintenanceStatus: 'good',
    status: 'available',
    location: { lat: C.lat - 0.008, lng: C.lng + 0.01 },
  },
  {
    id: 'veh-3',
    name: 'Unit 103',
    address: '500 Park Ave, New York, NY',
    type: 'Mini Bus',
    capacity: 14,
    wheelchairCapacity: 2,
    oxygenEquipment: false,
    liftAvailable: true,
    bariatricCapable: false,
    stretcherCapable: false,
    fuelType: 'Diesel',
    maintenanceStatus: 'due-soon',
    status: 'available',
    location: { lat: C.lat + 0.012, lng: C.lng + 0.014 },
  },
  {
    id: 'veh-4',
    name: 'Unit 104',
    address: '600 5th Ave, New York, NY',
    type: 'Shuttle Bus',
    capacity: 20,
    wheelchairCapacity: 2,
    oxygenEquipment: false,
    liftAvailable: true,
    bariatricCapable: false,
    stretcherCapable: false,
    fuelType: 'Electric',
    maintenanceStatus: 'good',
    status: 'available',
    location: { lat: C.lat - 0.014, lng: C.lng - 0.012 },
  },
  {
    id: 'veh-5',
    name: 'Unit 105',
    address: '800 Lexington Ave, New York, NY',
    type: 'Van',
    capacity: 8,
    wheelchairCapacity: 0,
    oxygenEquipment: false,
    liftAvailable: false,
    bariatricCapable: false,
    stretcherCapable: false,
    fuelType: 'Gas',
    maintenanceStatus: 'good',
    status: 'available',
    location: { lat: C.lat + 0.018, lng: C.lng - 0.004 },
  },
  {
    id: 'veh-6',
    name: 'Unit 106',
    address: '350 3rd Ave, New York, NY',
    type: 'SUV',
    capacity: 5,
    wheelchairCapacity: 0,
    oxygenEquipment: false,
    liftAvailable: false,
    bariatricCapable: false,
    stretcherCapable: false,
    fuelType: 'Hybrid',
    maintenanceStatus: 'good',
    status: 'available',
    location: { lat: C.lat - 0.006, lng: C.lng - 0.018 },
  },
  {
    id: 'veh-7',
    name: 'Unit 107',
    address: '1000 2nd Ave, New York, NY',
    type: 'Wheelchair Accessible Van',
    capacity: 6,
    wheelchairCapacity: 3,
    oxygenEquipment: true,
    liftAvailable: true,
    bariatricCapable: true,
    stretcherCapable: true,
    fuelType: 'Hybrid',
    maintenanceStatus: 'service-required',
    status: 'offline',
    location: { lat: C.lat + 0.02, lng: C.lng + 0.02 },
  },
  {
    id: 'veh-8',
    name: 'Unit 108',
    address: '750 Amsterdam Ave, New York, NY',
    type: 'Ambulance',
    capacity: 2,
    wheelchairCapacity: 0,
    oxygenEquipment: true,
    liftAvailable: true,
    bariatricCapable: false,
    stretcherCapable: true,
    fuelType: 'Diesel',
    maintenanceStatus: 'good',
    status: 'available',
    location: { lat: C.lat - 0.002, lng: C.lng + 0.02 },
  },
]

export const seedDrivers: Driver[] = [
  {
    id: 'drv-1',
    name: 'Carlos Mendez',
    phone: '(212) 555-0301',
    address: '400 Metro Ave, New York, NY',
    location: { lat: 40.7561, lng: -73.9855 },
    license: 'CDL-A 88213',
    certifications: { wheelchairAssist: true, medicalTransport: true },
    assignedVehicleId: 'veh-1',
    status: 'available',
    rating: 4.9,
    shiftStart: '06:00',
    shiftEnd: '14:00',
    shiftDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'drv-2',
    name: 'Aisha Bello',
    phone: '(212) 555-0302',
    address: '88 Riverside Blvd, Newark, NJ',
    location: { lat: 40.7358, lng: -74.1729 },
    license: 'CDL-B 44120',
    certifications: { wheelchairAssist: true, medicalTransport: true },
    assignedVehicleId: 'veh-2',
    status: 'available',
    rating: 4.8,
    shiftStart: '07:00',
    shiftEnd: '15:00',
    shiftDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'drv-3',
    name: 'Sergei Volkov',
    phone: '(212) 555-0303',
    address: '210 Maple St, Jersey City, NJ',
    location: { lat: 40.7178, lng: -74.0431 },
    license: 'CDL-B 71922',
    certifications: { wheelchairAssist: true, medicalTransport: false },
    assignedVehicleId: 'veh-3',
    status: 'available',
    rating: 4.6,
    shiftStart: '08:00',
    shiftEnd: '16:00',
    shiftDays: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'drv-4',
    name: 'Monica Reyes',
    phone: '(212) 555-0304',
    address: '15 Sunset Way, Brooklyn, NY',
    location: { lat: 40.6782, lng: -73.9442 },
    license: 'CDL-B 55018',
    certifications: { wheelchairAssist: true, medicalTransport: false },
    assignedVehicleId: 'veh-4',
    status: 'available',
    rating: 4.7,
    shiftStart: '09:00',
    shiftEnd: '17:00',
    shiftDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'drv-5',
    name: 'Derek Chan',
    phone: '(212) 555-0305',
    address: '77 Union Plaza, Queens, NY',
    location: { lat: 40.7262, lng: -73.7949 },
    license: 'Class D 90211',
    certifications: { wheelchairAssist: false, medicalTransport: false },
    assignedVehicleId: 'veh-5',
    status: 'available',
    rating: 4.5,
    shiftStart: '12:00',
    shiftEnd: '20:00',
    shiftDays: [1, 2, 3, 4, 5],
  },
  {
    id: 'drv-6',
    name: 'Fatima Noor',
    phone: '(212) 555-0306',
    address: '512 Northgate Rd, White Plains, NY',
    location: { lat: 41.0339, lng: -73.7629 },
    license: 'Class D 30877',
    certifications: { wheelchairAssist: false, medicalTransport: false },
    assignedVehicleId: 'veh-6',
    status: 'available',
    rating: 4.8,
    shiftStart: '13:00',
    shiftEnd: '21:00',
    shiftDays: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 'drv-7',
    name: 'Liam Doyle',
    phone: '(212) 555-0307',
    address: '640 Harbor Dr, Staten Island, NY',
    location: { lat: 40.5795, lng: -74.1502 },
    license: 'CDL-A 12009',
    certifications: { wheelchairAssist: true, medicalTransport: true },
    assignedVehicleId: 'veh-8',
    status: 'available',
    rating: 4.9,
    shiftStart: '22:00',
    shiftEnd: '06:00',
    shiftDays: [0, 1, 2, 3, 4, 5, 6],
  },
  {
    id: 'drv-8',
    name: 'Yuki Tanaka',
    phone: '(212) 555-0308',
    address: '900 Market St, Philadelphia, PA',
    location: { lat: 39.9533, lng: -75.1638 },
    license: 'CDL-B 66431',
    certifications: { wheelchairAssist: true, medicalTransport: true },
    assignedVehicleId: null,
    status: 'break',
    rating: 4.7,
    shiftStart: '06:00',
    shiftEnd: '14:00',
    shiftDays: [1, 2, 3, 4, 5],
  },
]

const today = new Date().toISOString().slice(0, 10)

export const seedEvents: FleetEvent[] = [
  {
    id: 'evt-1',
    name: 'Morning Dialysis Session',
    type: 'Dialysis Session',
    centerId: 'ctr-2',
    date: today,
    startTime: '08:30',
    endTime: '12:30',
    expectedAttendance: 10,
    participantIds: [
      'p-1',
      'p-2',
      'p-3',
      'p-4',
      'p-5',
      'p-6',
      'p-7',
      'p-8',
      'p-9',
      'p-10',
    ],
    roundTrip: true,
    returnTime: '12:30',
    status: 'active',
  },
  {
    id: 'evt-2',
    name: 'Afternoon Therapy Block',
    type: 'Therapy Session',
    centerId: 'ctr-6',
    date: today,
    startTime: '13:00',
    endTime: '16:00',
    expectedAttendance: 6,
    participantIds: ['p-11', 'p-12', 'p-13', 'p-14', 'p-15', 'p-16'],
    roundTrip: true,
    returnTime: '16:00',
    status: 'planning',
  },
  {
    id: 'evt-3',
    name: 'Community Vaccination Camp',
    type: 'Vaccination Camp',
    centerId: 'ctr-5',
    date: today,
    startTime: '10:00',
    endTime: '15:00',
    expectedAttendance: 40,
    participantIds: [],
    status: 'scheduled',
  },
  {
    id: 'evt-4',
    name: 'Rehab Group Session',
    type: 'Rehabilitation Session',
    centerId: 'ctr-3',
    date: today,
    startTime: '09:00',
    endTime: '11:00',
    expectedAttendance: 12,
    participantIds: [],
    status: 'scheduled',
  },
  {
    id: 'evt-5',
    name: 'Senior Health Screening',
    type: 'Health Screening',
    centerId: 'ctr-4',
    date: today,
    startTime: '11:00',
    endTime: '14:00',
    expectedAttendance: 24,
    participantIds: [],
    status: 'scheduled',
  },
]

// Meal-delivery runs: the fleet collects prepared meals from a kitchen/center
// and drops them at participants' homes. seed.ts turns these lightweight configs
// into full rows (with OSRM route paths and per-stop meal counts).
export interface SeedMealRun {
  id: string
  runNumber: string
  centerId: string
  vehicleId: string
  driverId: string
  departTime: string
  mealType: 'Breakfast' | 'Lunch' | 'Dinner'
  participantIds: string[]
  status: 'scheduled' | 'preparing' | 'loaded' | 'en-route' | 'delivering' | 'completed'
  progress: number
}

export const seedMealRuns: SeedMealRun[] = [
  {
    id: 'meal-1',
    runNumber: 'MD-2001',
    centerId: 'ctr-4',
    vehicleId: 'veh-4',
    driverId: 'drv-4',
    departTime: '11:15',
    mealType: 'Lunch',
    participantIds: ['p-1', 'p-3', 'p-5', 'p-7', 'p-9'],
    status: 'en-route',
    progress: 0.35,
  },
  {
    id: 'meal-2',
    runNumber: 'MD-2002',
    centerId: 'ctr-1',
    vehicleId: 'veh-5',
    driverId: 'drv-5',
    departTime: '11:30',
    mealType: 'Lunch',
    participantIds: ['p-2', 'p-4', 'p-6', 'p-8'],
    status: 'delivering',
    progress: 0.6,
  },
  {
    id: 'meal-3',
    runNumber: 'MD-2003',
    centerId: 'ctr-4',
    vehicleId: 'veh-6',
    driverId: 'drv-6',
    departTime: '17:00',
    mealType: 'Dinner',
    participantIds: ['p-11', 'p-13', 'p-15', 'p-17', 'p-19'],
    status: 'scheduled',
    progress: 0,
  },
]
